apiVersion: database.entigo.com/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: mydatabase
spec:
  allocatedStorage: 20
  engineVersion: '18.6'
  instanceType: 'db.t3.small'
  deletionProtection: false
